### ISSUE TITLE
现在是否还能从手机上找到wxapkg包？

### ISSUE THREAD

**Issue by lecer** [leo9960/wechat-app-unpack#18]
今天在手机上找了下，没有找到，看日期18年1月8日，被公布了漏洞，不知道是否是更换了形式。

**Comment by jsnjfz** [comment]
昨天还能找到，手机需要root。最简单的方法是下个安卓模拟器(比如夜神)，直接去相应目录下找就可以了

**Comment by lecer** [comment]
谢谢，我试下是不是光用夜神就可以，我手机是联想的，ROOT不了，刚才用小米ROOT过的手机找也没找到，按/data/.../Micro../appBrand/下的路径找的

**Comment by jsnjfz** [comment]
用模拟器最简单了，默认自带root，用各种脚本外挂也方便

**Comment by lecer** [comment]
非常感谢！
