### ISSUE TITLE
解到m13发现一个错误

### ISSUE THREAD

**Issue by mychenjun** [leo9960/wechat-app-unpack#8]
var m13=function(e,s,r,gg){
var lQ4=e_[x[13]].i
_ai(lQ4,x[14],e_,x[13],1,1)
var aR4=_m('view',['class',1107,'style',1],[],e,s,gg)
var tS4=_v()
_(aR4,tS4)
var eT4=_o(1110,e,s,gg)
var bU4=_gd(x[13],eT4,e_,d_)
if(bU4){
var oV4=_1(1109,e,s,gg) || {}
var cur_globalf=gg.f
tS4.wxXCkey=3
bU4(oV4,oV4,tS4,gg)
gg.f=cur_globalf
}
else _w(eT4,x[13],3,22)
_(r,aR4)
lQ4.pop()
return r
}

错误内容：
test.html:2748 Uncaught ReferenceError: x is not defined
    at m13 (test.html:2748)
    at test.html:16740

**Comment by mychenjun** [comment]
知道了，template模板组件还无法解析

**Comment by mychenjun** [comment]
变量替换的问题没有更新进去吗？不是有人发出了觪决方法。

**Comment by leo9960** [comment]
我正在研究能否一次性解出所有wxml

**Comment by zizoloziz** [comment]
js有类似Java的反射机制吗
